import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc/#/');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).click();
  await page.getByRole('textbox', { name: 'What needs to be done?' }).fill('Wäsche waschen');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).press('Enter');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).fill('Spülen');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).press('Enter');
  await expect(page.locator('body')).toContainText('Wäsche waschenSpülen');
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Spülen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await page.getByRole('button', { name: 'Delete' }).click();
  await expect(page.locator('body')).not.toContainText('Spülen');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).click();
  await page.getByRole('textbox', { name: 'What needs to be done?' }).fill('Gym');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).press('Enter');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).fill('Mama besuchen');
  await page.getByRole('textbox', { name: 'What needs to be done?' }).press('Enter');
  await expect(page.locator('body')).toContainText('This is just a demo of TodoMVC for testing, not the real TodoMVC app. todosMark all as completeWäsche waschenGymMama besuchen3 items leftAll Active Completed Double-click to edit a todo Created by Remo H. Jansen Part of TodoMVC');
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Gym' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Mama besuchen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await page.getByText('Mark all as complete').click();
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Gym' }).getByLabel('Toggle Todo')).toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Mama besuchen' }).getByLabel('Toggle Todo')).toBeChecked();
  await page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo').uncheck();
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Gym' }).getByLabel('Toggle Todo')).toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Mama besuchen' }).getByLabel('Toggle Todo')).toBeChecked();
  await page.getByText('Mark all as complete').click();
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Gym' }).getByLabel('Toggle Todo')).toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Mama besuchen' }).getByLabel('Toggle Todo')).toBeChecked();
  await page.getByText('Mark all as complete').click();
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Gym' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await expect(page.getByRole('listitem').filter({ hasText: 'Mama besuchen' }).getByLabel('Toggle Todo')).not.toBeChecked();
  await page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo').check();
  await expect(page.getByRole('listitem').filter({ hasText: 'Wäsche waschen' }).getByLabel('Toggle Todo')).toBeChecked();
  await expect(page.locator('body')).toContainText('This is just a demo of TodoMVC for testing, not the real TodoMVC app. todosMark all as completeWäsche waschenGymMama besuchen2 items leftAll Active CompletedClear completed Double-click to edit a todo Created by Remo H. Jansen Part of TodoMVC');
  await page.getByRole('button', { name: 'Clear completed' }).click();
  await expect(page.locator('body')).toContainText('This is just a demo of TodoMVC for testing, not the real TodoMVC app. todosMark all as completeGymMama besuchen2 items leftAll Active Completed Double-click to edit a todo Created by Remo H. Jansen Part of TodoMVC');
});